import dev.whyoleg.kamp.module.*

//Autogenerated with kamp, don't change

object Modules {
    val plugin = Module(":plugin")

    object Deps {
        val st = Module(":deps:st")
        val dev = Module(":deps:dev")
    }
}
